version: "3.8"

services:
  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-api
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 5
      KEEP_HISTORY: 1
      PROJECT_NAME: "Template Testes Automatizados"
    volumes:
      - allure-results-volume:/app/projects
    restart: always

  allure-ui:
    image: frankescobar/allure-docker-service-ui
    container_name: allure-dashboard
    ports:
      - "5252:5252"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_PROJECT_ID: "default"
      PORT: 5252
    depends_on:
      - allure
    restart: always

volumes:
  allure-results-volume:
